/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BallAndStrike: typeof import('./src/components/controls/BallAndStrike.vue')['default']
    Bases: typeof import('./src/components/controls/Bases.vue')['default']
    ControlBoard: typeof import('./src/components/ControlBoard.vue')['default']
    Controls: typeof import('./src/components/Controls.vue')['default']
    FirstHalf: typeof import('./src/components/middlepart/FirstHalf.vue')['default']
    IncDecButtons: typeof import('./src/components/controls/IncDecButtons.vue')['default']
    Inning: typeof import('./src/components/controls/Inning.vue')['default']
    InningTriangle: typeof import('./src/components/shapes/InningTriangle.vue')['default']
    MarginWrapper: typeof import('./src/components/MarginWrapper.vue')['default']
    MiddlePart: typeof import('./src/components/middlepart/MiddlePart.vue')['default']
    Outs: typeof import('./src/components/controls/Outs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scoreboard: typeof import('./src/components/Scoreboard.vue')['default']
    Scorebox: typeof import('./src/components/Scorebox.vue')['default']
    SecondHalf: typeof import('./src/components/middlepart/SecondHalf.vue')['default']
    TeamScores: typeof import('./src/components/controls/TeamScores.vue')['default']
    WebTitle: typeof import('./src/components/WebTitle.vue')['default']
  }
}
